/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_javacallc_JavaCallCJNI */

#ifndef _Included_com_example_javacallc_JavaCallCJNI
#define _Included_com_example_javacallc_JavaCallCJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_javacallc_JavaCallCJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_javacallc_JavaCallCJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_javacallc_JavaCallCJNI
 * Method:    getMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_javacallc_JavaCallCJNI_getMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_javacallc_JavaCallCJNI
 * Method:    checkPassword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_javacallc_JavaCallCJNI_checkPassword
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
